services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: echotask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    image: echo-task-spring-boot
    container_name: echo-task-spring-boot
    env_file:
      - backend/.env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: echo-task-react
    container_name: echo-task-react
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
